import localFont from "next/font/local";
import type { Metadata } from "next";
import "./globals.css";
import DevToolsBlocker from "./DevToolsBlocker";

const starlight = localFont({
  src: "./font/STARLIGHT-PERSONAL.woff2",
  variable: "--font-starlight",
  display: "swap",
});


export const metadata: Metadata = {
  icons: {
    icon: "/icon.svg",
    apple: "/icon.svg",
    shortcut: "/icon.svg",
  },
  title: "Huskeroonies",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={starlight.variable}>
       {/* <DevToolsBlocker />  */}
      <body>{children}</body>
    </html>
  );
}