import type { Metadata } from "next";
import { Potta_One } from "next/font/google";
import "./globals.css";
// import "./flip-book/flip-book.module.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const pottaOne = Potta_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-potta-one",
});

export const metadata: Metadata = {
  icons: {
    icon: "/icon.svg",
    apple: "/icon.svg",
    shortcut: "/icon.svg",
  },
  title: "Huskeroonies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={pottaOne.variable}>
      <body>{children}</body>
    </html>
  );
}